# Generated by Django 3.2.6 on 2021-08-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='seo_id',
            new_name='seo',
        ),
        migrations.RenameField(
            model_name='contactpage',
            old_name='seo_id',
            new_name='seo',
        ),
        migrations.RenameField(
            model_name='mainpage',
            old_name='seo_id',
            new_name='seo',
        ),
        migrations.RenameField(
            model_name='servicepage',
            old_name='seo_id',
            new_name='seo',
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='description',
            field=models.TextField(verbose_name='Краткий текст'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
