# Generated by Django 3.2.6 on 2021-08-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20210818_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_additional',
            field=models.BooleanField(blank=True, default=False, verbose_name='Дополнительная галерея'),
        ),
    ]
