# Generated by Django 3.2.6 on 2021-08-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_gallery_is_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
