# Generated by Django 3.2.6 on 2021-09-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0007_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткий текст'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='link_commercial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на коммерческий сайт'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='map',
            field=models.TextField(blank=True, null=True, verbose_name='Код карты'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='description',
            field=models.TextField(verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название услуги'),
        ),
    ]
