# Generated by Django 3.2.6 on 2021-09-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0008_auto_20210902_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ед. изм.')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Услуга')),
                ('show', models.BooleanField(verbose_name='Показывать в счетчиках')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.unit')),
            ],
        ),
    ]
