# Generated by Django 3.2.6 on 2021-09-08 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0009_auto_20210906_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('description', models.TextField(verbose_name='Описание тарифа')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.unit'),
        ),
        migrations.CreateModel(
            name='TariffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('currency', models.CharField(default='грн', max_length=5, verbose_name='Валюта')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.service')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.tariff')),
            ],
        ),
    ]
