# Generated by Django 3.2.6 on 2021-09-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0010_auto_20210908_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffservice',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
