# Generated by Django 3.2.6 on 2021-09-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0011_tariffservice_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffservice',
            name='updated',
        ),
        migrations.AddField(
            model_name='tariff',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
