# Generated by Django 3.2.6 on 2021-09-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0012_auto_20210908_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['id']},
        ),
    ]
