# Generated by Django 3.2.6 on 2021-09-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0013_alter_tariff_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название компании')),
                ('information', models.TextField(verbose_name='Информация')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
