# Generated by Django 3.2.6 on 2021-09-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0014_requisites'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('type', models.CharField(choices=[('расходы', 'расходы'), ('приходы', 'приходы')], max_length=30, verbose_name='Приходы/Расходы')),
            ],
        ),
    ]
