# Generated by Django 3.2.6 on 2021-09-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0015_paymentitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('levels', models.ManyToManyField(to='admin.Level')),
                ('sections', models.ManyToManyField(to='admin.Section')),
            ],
        ),
    ]
