# Generated by Django 3.2.6 on 2021-09-13 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0017_auto_20210913_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='house',
            name='sections',
        ),
        migrations.AddField(
            model_name='level',
            name='house',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin.house'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin.house'),
            preserve_default=False,
        ),
    ]
