# Generated by Django 3.2.6 on 2021-09-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210910_1246'),
        ('admin', '0018_auto_20210913_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='users',
            field=models.ManyToManyField(to='account.Profile'),
        ),
    ]
