# Generated by Django 3.2.6 on 2021-09-13 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0019_house_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_level', to='admin.house'),
        ),
    ]
