# Generated by Django 3.2.6 on 2021-09-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0021_rename_name_level_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='title',
            new_name='name',
        ),
    ]
