# Generated by Django 3.2.6 on 2021-09-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0025_alter_flat_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='house',
        ),
    ]
