# Generated by Django 3.2.6 on 2021-09-17 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0031_alter_counter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='date',
            field=models.DateField(default=datetime.date(2021, 9, 17)),
        ),
    ]
