# Generated by Django 3.2.6 on 2021-09-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0032_counter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер квартиры'),
        ),
    ]
