# Generated by Django 3.2.6 on 2021-09-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0034_alter_counter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
