# Generated by Django 3.2.6 on 2021-09-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0036_alter_counter_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBook',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='№')),
                ('status', models.CharField(choices=[('Активен', 'Активен'), ('Неактивен', 'Неактивен')], max_length=20, verbose_name='Статус')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.flat', verbose_name='Квартира')),
            ],
        ),
    ]
