# Generated by Django 3.2.6 on 2021-09-21 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210915_1642'),
        ('admin', '0037_bankbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='№')),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=True, verbose_name='Проведен')),
                ('type', models.CharField(choices=[('приход', 'приход'), ('расход', 'расход')], max_length=10, verbose_name='Приход/Расход')),
                ('amount_of_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма(грн)')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('bankbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.bankbook', verbose_name='Лицевой счет')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.profile')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.paymentitem', verbose_name='Тип платежа')),
            ],
        ),
    ]
