# Generated by Django 3.2.6 on 2021-09-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0038_cashbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
