# Generated by Django 3.2.6 on 2021-09-22 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0039_alter_cashbox_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='№')),
                ('date', models.DateField()),
                ('date_from', models.DateField(verbose_name='Период с')),
                ('date_to', models.DateField(verbose_name='Период по')),
                ('is_checked', models.BooleanField(default=True, verbose_name='Проведена')),
                ('status', models.CharField(choices=[('оплачена', 'оплачена'), ('частично оплачена', 'частично оплачена'), ('не оплачена', 'не оплачена')], max_length=20, verbose_name='Статус')),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.flat', verbose_name='Квартира')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Расход')),
                ('price_unit', models.FloatField(verbose_name='Цеа за 1 ед., грн.')),
                ('price', models.FloatField(verbose_name='Стоимость, грн.')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.receipt')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin.service')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.unit')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='services',
            field=models.ManyToManyField(through='admin.ReceiptService', to='admin.Service'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.tariff', verbose_name='Тариф'),
        ),
    ]
