# Generated by Django 3.2.6 on 2021-09-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0040_auto_20210922_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='bank_book',
        ),
    ]
