# Generated by Django 3.2.6 on 2021-09-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0045_auto_20210927_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
