# Generated by Django 3.2.6 on 2021-09-28 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0047_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='has_debt',
            field=models.BooleanField(default=False, verbose_name='Владельцам с задолженностями'),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='admin.unit'),
        ),
    ]
