# Generated by Django 3.2.6 on 2021-09-28 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0048_auto_20210928_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='admin.paymentitem', verbose_name='Тип платежа'),
        ),
    ]
