# Generated by Django 3.2.6 on 2021-09-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_owner_status'),
        ('admin', '0050_auto_20210929_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.owner', verbose_name='Владелец квартир'),
        ),
    ]
