# Generated by Django 3.2.6 on 2021-10-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0051_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbook',
            name='status',
            field=models.CharField(choices=[(None, ''), ('Активен', 'Активен'), ('Неактивен', 'Неактивен')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='type',
            field=models.CharField(choices=[(None, ''), ('приход', 'приход'), ('расход', 'расход')], max_length=10, verbose_name='Приход/Расход'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[(None, ''), ('оплачена', 'оплачена'), ('частично оплачена', 'частично оплачена'), ('не оплачена', 'не оплачена')], max_length=20, verbose_name='Статус'),
        ),
    ]
