# Generated by Django 3.2.6 on 2021-10-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0052_auto_20211001_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrequest',
            name='status',
            field=models.CharField(blank=True, choices=[(None, ''), ('новое', 'новое'), ('в процессе', 'в процессе'), ('выполнено', 'выполнено')], default='новое', max_length=30, verbose_name='Статус'),
        ),
    ]
