# Generated by Django 3.2.6 on 2021-09-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('активен', 'активен'), ('новый', 'новый'), ('отключен', 'отключен')], default='новый', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('директор', 'директор'), ('управляющий', 'управляющий'), ('бухгалтер', 'бухгалтер'), ('электрик', 'электрик'), ('сантехник', 'сантехник')], default='директор', max_length=20, verbose_name='Роль'),
        ),
    ]
