# Generated by Django 3.2.6 on 2021-09-15 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20210910_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='owners/', verbose_name='Сменить изображение')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('viber', models.CharField(max_length=50, verbose_name='Viber')),
                ('telegram', models.CharField(max_length=50, verbose_name='Telegram')),
                ('identify', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='ID')),
                ('status', models.CharField(choices=[('активен', 'активен'), ('новый', 'новый'), ('отключен', 'отключен')], default='новый', max_length=20, verbose_name='Статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
