# Generated by Django 3.2.6 on 2021-09-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_owner_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
