# Generated by Django 3.2.6 on 2021-09-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210915_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='status',
            field=models.CharField(choices=[(None, ''), ('активен', 'активен'), ('новый', 'новый'), ('отключен', 'отключен')], default='новый', max_length=20, verbose_name='Статус'),
        ),
    ]
