# Generated by Django 3.2.6 on 2021-10-01 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_owner_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.permissionpage')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.BooleanField()),
                ('role', models.CharField(choices=[('директор', 'директор'), ('управляющий', 'управляющий'), ('бухгалтер', 'бухгалтер'), ('электрик', 'электрик'), ('сантехник', 'сантехник')], max_length=100)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.permissionpage')),
            ],
        ),
    ]
